FROM --platform=${TARGETPLATFORM:-linux/amd64} alpine:edge AS build
RUN apk add --no-cache \
    crystal \
    shards \
    yaml-dev \
    yaml-static \
    openssl-dev \
    openssl-libs-static \
    libxml2-dev \
    libxml2-static \
    zlib-dev \
    zlib-static \
    xz-dev \
    xz-static \
    gc-static \
    gc-dev \
    pcre2-dev \
    pcre2-static \
    make
